import type { Metadata } from "next";
import "./globals.css";

import NavButton from "@/components/custom/NavButton";
import { Button } from "@/components/ui/button";

import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import Link from "next/link";

import { TbBrandThreads } from "react-icons/tb";
import { CgMenuRightAlt } from "react-icons/cg";
import { BiArrowBack } from "react-icons/bi";
import { RiInstagramLine } from "react-icons/ri";

import Aside from "@/components/custom/Aside";
import { ThemeProvider } from "@/components/custom/theme-provider";
import PlusBtn from "@/components/custom/PlusBtn";
import SessionProvider from "@/components/custom/SessionProvider";
import { getServerSession } from "next-auth";
import { signIn } from "next-auth/react";
import RegisterBtn, { MiniBtnRegister } from "@/components/custom/RegisterBtn";


export const metadata: Metadata = {
	title: "Home . Threads",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {


	const session = await getServerSession()

	return (
		<html lang="en" suppressHydrationWarning>
			<body className="md:overflow-hidden" >
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<SessionProvider session={session}>

						<div className="p-4 pb-0 antialiased  items-end justify-between w-full  md:flex  relative">
							<Aside />

							<header className="h-[65px] w-full fixed top-0 left-0 pt-4 pb-5 px-4 backdrop-blur-[10px]  bg-[rgba(0,0,0,0.69)] md:hidden">

								<div className="flex  items-center justify-between">
									<Link href={"/"}>
										<BiArrowBack size={22} className="text-[#4d4d4d] cursor-pointer w-[55px] hover:text-white animate movie opacity-0" />
									</Link>
									<Link href="/">
										<TbBrandThreads color="white" size={34} className="hover:scale-[1.1] animate" />
									</Link>

								<MiniBtnRegister/>
								</div>
							</header>

							<div className="flex items-start gap-2 mx-auto mt-15   md:mt-0" >

								<div className="w-full md:w-fit">
									<p className="text-white font-semibold text-center mb-4 hidden md:block">Главная</p>
									<main className="overflow-y-auto text-white  w-full mx-auto bg-black md:bg-[#101010]  md:h-[90vh] md:w-[550px] rounded-2xl rounded-b-[0px] py-6 px-1 md:px-5  scroll-none">

										{children}
									</main>
								</div>
								<RegisterBtn />
								<div className="hidden md:block">
									<MiniBtnRegister />
								</div>
							</div>

							<button className="hidden text-white">+</button>

							<NavButton />


							<PlusBtn />
						</div>

					</SessionProvider>
				</ThemeProvider>

			</body>
		</html>
	);
}
